New/search
folkehelseinstituttet/Fhi.Frontend.Demo pull request #122
Opened 2022-09-08 10:59 UTC by yleaxeman

2022-09-08 13:44 UTC, proand commented on src/MOCK_DB_DATA/library-items/search/search.ts
> +<div class="fhi-search"><!-- add fhi-search--xl for tall search field -->
This should be the angular example...

2022-09-08 13:44 UTC, proand commented on src/app/views/developer/developer.component.ts
> +        return this.getComponentsMenu();
Thanks 👍

2022-09-08 13:44 UTC, proand commented on src/app/views/shared/dynamic-library-examples/fhi-angular-examples/search-example/search-example.component.ts
> +const countries = ['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Anguilla', 'Antarctica', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria'
...but no need to break line here, ok when just dummy data ;)

2022-09-08 13:48 UTC, yleaxeman commented on src/app/views/shared/dynamic-library-examples/fhi-angular-examples/search-example/search-example.component.html
> +      <input id="typeahead-basic" type="search" class="form-control fhi-search__form-control" placeholder="Start searching..." [(ngModel)]="model" [ngbTypeahead]="search"/>
What's the rule?

2022-09-08 13:51 UTC, proand commented on src/app/views/shared/dynamic-library-examples/fhi-angular-examples/search-example/search-example.component.html
> +      <input id="typeahead-basic" type="search" class="form-control fhi-search__form-control" placeholder="Start searching..." [(ngModel)]="model" [ngbTypeahead]="search"/>
We havent' established a hard rule... we probably should. Many projects use 140, I think 100 is enough...

2022-09-08 13:52 UTC, proand commented on src/app/views/shared/dynamic-library-examples/fhi-angular-examples/search-example/search-example.component.html
> +      <input id="typeahead-basic" type="search" class="form-control fhi-search__form-control" placeholder="Start searching..." [(ngModel)]="model" [ngbTypeahead]="search"/>
...and aligning the attributes when more than one line.

2022-09-08 14:10 UTC, yleaxeman commented on src/MOCK_DB_DATA/library-items/search/search.ts
> +<div class="fhi-search"><!-- add fhi-search--xl for tall search field -->
Like this?...

2022-09-08 14:14 UTC, yleaxeman commented on src/app/views/shared/dynamic-library-examples/fhi-angular-examples/search-example/search-example.component.html
> +      <input id="typeahead-basic" type="search" class="form-control fhi-search__form-control" placeholder="Start searching..." [(ngModel)]="model" [ngbTypeahead]="search"/>
Is there some kind of config that could take care of this?

2022-09-09 07:25 UTC, proand requested changes

2022-09-09 07:25 UTC, proand commented on package.json
> +  "version": "3.8.0",
Skip this... I think the version should be 1.0.0 when we do the "relaunch" of the FHI Designsystem...

2022-09-09 07:27 UTC, proand approved these changes
👍

2022-09-09 07:31 UTC, merged